config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :adverts
  devise_for :users

  root 'home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advert.rb
class Advert < ApplicationRecord
  JOB_TYPES = %w[full_time part_time].freeze
  ADVERT_TYPES = %w[job care].freeze
  belongs_to :user
  has_many :locations, inverse_of: :advert
  accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true, length: { minimum: 2, maximum: 200 }
  validates :description, presence: true, length: { minimum: 2, maximum: 400 }
  validates :city, presence: true
  validates :street, presence: true
  validates :phone, presence: true,
                    format: { with: /[1-9]\d*\d{8}/,
                              message: "please type in format: '123456789'" }

  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :job_type, presence: true, inclusion: %w[full_time part_time]
  validates :advert_type, presence: true, inclusion: %w[job care]

  scope :by_advert_type, ->(type) { where "advert_type": type.to_s if type.present? }
  scope :by_job_type, ->(type) { where "job_type": type.to_s if type.present? }
  scope :by_city, ->(city) { where "city": city.to_s if city.present? }
  scope :by_price, ->(price) { where("price < ?", price) if price.present? }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  belongs_to :advert
end

app/models/user.rb
class User < ApplicationRecord
  has_many :adverts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true, length: { in: 2..30 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :phone, presence: true,
                    format: { with: /[1-9]\d*\d{8}/,
                              message: "please type in format: '123456789'" }
  validates :city, presence: true
  validates :street, presence: true

  has_attached_file :avatar, styles: { medium: "270x270#", small: "160x150#" },
                             default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: %r{\Aimage\/.*\z}
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  before_action :check_advert_belongs_to_current_user, only: %i[edit update destroy]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all
    @adverts = @adverts.by_advert_type(search_params[:advert_type])
    @adverts = @adverts.by_job_type(search_params[:job_type])
    @adverts = @adverts.by_city(search_params[:city])
    @adverts = @adverts.by_price(search_params[:price])
    @adverts = @adverts.paginate(page: params[:page], per_page: 5)
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show; end

  # GET /adverts/new
  def new
    @advert = current_user.adverts.build
  end

  # GET /adverts/1/edit
  def edit; end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = current_user.adverts.build(advert_params)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: "Advert was successfully created." }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: "Advert was successfully updated." }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: "Advert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def search_params
    params.permit(search: %i[advert_type job_type city price]).fetch(:search, {})
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_advert
    @advert = Advert.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def advert_params
    params.require(:advert)
          .permit(:advert_type, :title, :description, :city, :street, :phone,
                  :price, :job_type, :advert_type, locations_attributes:
                  %i[id address destroy])
  end

  def check_advert_belongs_to_current_user
    @advert = current_user.adverts.find_by(id: params[:id])
    redirect_to adverts_path, notice: "Hey, that is not your advert!" if @advert.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[first_name last_name email phone city street avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs << :avatar_cache
    devise_parameter_sanitizer.permit :sign_in, keys: %i[email password]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about; end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show edit update destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show; end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit; end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params.require(:location).permit(:address, :latitude, :longitude)
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/adverts/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading
        %h2 New ad
      .panel-body
        = simple_form_for @advert do |f|
          = f.error_notification
          .form-group

            = f.input :advert_type, required: true, collection: ['job', 'care'],
                       label: 'Looking for', input_html: { class: 'form-control' }
            = f.input :title, required: true, input_html: { class: 'form-control' }
            = f.input :description, required: true, input_html: { class: 'form-control' }
            = f.input :price, required: true, label: 'Price per hour',
                       input_html: { class: 'form-control' }
            = f.input :job_type, required: true, collection: ['full_time', 'part_time'],
                      label: 'Choose job type', input_html: { class: 'form-control' }
            = f.input :city, required: true, input_html: { class: 'form-control' }
            = f.input :street, required: true, input_html: { class: 'form-control' }
            = f.input :phone, required: true, input_html: { class: 'form-control' }
          %br/
          %h3 Locations
          #locations
          = f.simple_fields_for :locations do |location|
            = render 'location_fields', f: location

          .links
            = link_to_add_association 'Pin on map', f, :locations, class: "btn btn-default"

          .form-actions
            = f.button :submit, "Create", class: "btn btn-primary"
          %br/
      .panel-footer

app/views/adverts/_location_fields.html.haml
.nested-fields
  = f.input :address
  = link_to_remove_association "remove location", f

app/views/adverts/edit.html.haml
%h1 Editing advert

= render 'form'

= link_to 'Show', @advert
\|
= link_to 'Back', adverts_path

app/views/adverts/index.html.haml
= simple_form_for "search", url: adverts_path, input_html: { id: 'filter' },
                  method: 'get' do |f|
  = f.input :advert_type, required: true, collection: ['job', 'care'],
              label: false, prompt: 'Looking for'
  = f.input :job_type, required: true, collection: ['full_time', 'part_time'],
             label: false, prompt: 'Job type'
  = f.input :city, required: true, collection: Advert.distinct.all.pluck(:city),
             label: false, prompt: "City"
  = f.input :price, collection: 1..1000, label: false, prompt: "Price per hour"
  = f.button :submit, "Search", class: "btn btn-primary"

%ul
  -@adverts.each do |advert|
    %li.advert
      = link_to advert do
        .image-wrapper
          = image_tag advert.user.avatar.url(:small)
        .content-wrapper
          .title
            = advert.title
          .job-type
            = advert.job_type
          .location
            = advert.city + ', ' + advert.street
        .prize-wrapper
          = advert.price.to_s + '$ ph'
        .data-wrapper
          = advert.created_at.strftime("%d/%m/%Y")


= will_paginate @adverts,  renderer: BootstrapPagination::Rails

app/views/adverts/new.html.haml
%h1 New advert

= render 'form'

= link_to 'Back', adverts_path

app/views/adverts/show.html.haml
.container-advert
  .row
    %h2.title
      =@advert.title

    .col-md-4
      .image-wrapper
        = image_tag @advert.user.avatar.url(:medium)
    .col-md-6
      = link_to 'Edit', edit_advert_path(@advert) if @advert.user == current_user
      .description
        = @advert.description
  .row
    .col-md-4
      .phone
        = 'Phone: ' + @advert.phone
      .job-type
        = @advert.job_type

  .row
    .col-md-8.col-md-offset-2
      .map-label
        = @advert.locations.first.address
      .map
        = image_tag "http://maps.google.com/maps/api/staticmap?size=700x400&sensor=false&zoom=16&markers=#{@advert.locations.first.latitude}%2C#{@advert.locations.first.longitude}"

app/views/home/about.html.haml
%h1 Home#about
%p Find me in app/views/home/about.html.haml

app/views/home/index.html.haml
.question
  %h3
    I'm looking for:
  .answers
    .answer
      %h4= link_to 'Job', adverts_path( search:{"advert_type"=>"job", "job_type"=>"", "city"=>"", "price"=>""}),
        class: 'btn btn-primary'
    .answer
      %h4= link_to 'Care', adverts_path( search:{"advert_type"=>"care", "job_type"=>"", "city"=>"", "price"=>""}),
        class: 'btn btn-default'

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        .brand-label= link_to image_tag('logo_v1.png'), root_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to 'Post an Ad', new_advert_url, class: 'btn btn-primary'
          %li= link_to 'Account', edit_user_registration_path, class: 'btn btn-default'
          %li= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-default'
        - else
          %li= link_to 'Sign In', new_user_session_path, class: 'btn btn-default'
          %li= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BestNanny
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'

    - if notice
      #notice-wrapper
        %p#notice= notice
    - elsif alert
      #notice-wrapper
        %p#alert= alert

    .container
      = yield
    = render 'layouts/footer'

app/views/locations/_form.html.haml
= simple_form_for(@location) do |f|
  = f.error_notification

  .form-inputs
    = f.input :address
    = f.input :latitude
    = f.input :longitude

  .form-actions
    = f.button :submit

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table
  %thead
    %tr
      %th Address
      %th Latitude
      %th Longitude
      %th
      %th
      %th

  %tbody
    - @locations.each do |location|
      %tr
        %td= location.address
        %td= location.latitude
        %td= location.longitude
        %td= link_to 'Show', location
        %td= link_to 'Edit', edit_location_path(location)
        %td= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Address:
  = @location.address
%p
  %b Latitude:
  = @location.latitude
%p
  %b Longitude:
  = @location.longitude

#map
  = image_tag "http://maps.google.com/maps/api/staticmap?size=700x400&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}"


= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path

app/views/partial/_location_fields.html.haml
.nested-fields
  = f.input :address
  = link_to_remove_association "remove location", f